<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_shipment_by</name>
   <tag></tag>
   <elementGuidId>1f3e7d89-5243-4300-9158-203461e0ab54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'shipmentBy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a7fb05fd-6b7f-4146-9177-5ce7c09e8a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipmentBy</value>
      <webElementGuid>8f954b9f-f5ae-4d94-b903-3cf9fc6e1bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shipmentBy</value>
      <webElementGuid>7b1829b5-0f82-49ff-a792-b752419c973b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
