<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_to_consignee</name>
   <tag></tag>
   <elementGuidId>5ecfa83e-9ed8-4a6e-a45e-8c9107b99888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'toConsignee']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ab682cb-79c9-4563-8c38-cab7b71fe59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toConsignee</value>
      <webElementGuid>a6f1788a-9dcc-4565-b79b-21d4ceb6916b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
