<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_from_shipper</name>
   <tag></tag>
   <elementGuidId>1e54f4b7-b1fd-40f9-9c76-4b61efcd50fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fromShipper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>962daf9b-37fe-4e11-8b41-38812f1209d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fromShipper</value>
      <webElementGuid>2b7d36ad-9e35-40c8-97fc-9d6e5fca1501</webElementGuid>
   </webElementProperties>
</WebElementEntity>
