<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_gross_weight</name>
   <tag></tag>
   <elementGuidId>6791f355-d775-49c5-b11e-abfde44c1f3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@label = '* Gross Weight']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/div/div[1]/div[3]/div/div/div/div[2]/div/div/div[2]/form/div[1]/div[3]/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>480effdb-2f96-4948-a9b4-1b03ff75691d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>* Gross Weight</value>
      <webElementGuid>68dc5500-dfe9-40db-9ce6-706671224dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5fa35576-0159-4885-a32e-7d2ac6f0ba3e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
