<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_port_of_loading</name>
   <tag></tag>
   <elementGuidId>66876208-da4e-4fe6-9461-d063bf0e048d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'portOfLoading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff8d4721-22cb-4aa3-8c02-21e148715302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>portOfLoading</value>
      <webElementGuid>07306211-bb11-43ea-83e8-2bae2ce1c4ea</webElementGuid>
   </webElementProperties>
</WebElementEntity>
