<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_customer_address</name>
   <tag></tag>
   <elementGuidId>5facaa2e-88ae-49f7-9c30-bacf88065628</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[3]/div/div/div/div[2]/div/div/div[3]/div/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ql-editor.ql-blank</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.ql-editor</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>931b93a3-91bd-452c-9bb7-7f44df905b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ql-editor ql-blank</value>
      <webElementGuid>f2847ca6-9333-4a32-bf48-4335e9799e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gramm</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cf2bc91d-a9ec-4f6e-b1b1-50da7a2221ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>427c7cbc-a717-400f-9dba-9a665ea6e47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Type here ..</value>
      <webElementGuid>4ce9ab50-3b65-4154-bb48-c1f32ac78edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;horizontalMenucontainer&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;main-content side-content pt-0&quot;]/div[@class=&quot;main-container container-fluid&quot;]/div[@class=&quot;inner-body&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12&quot;]/div[@class=&quot;my-card-padding mb-mobile card&quot;]/div[@class=&quot;d-flex flex-column w-100 gap-2 my-5&quot;]/div[@class=&quot;d-flex flex-column justify-content-between responsive position-relative gap-3&quot;]/div[@class=&quot;mt-1&quot;]/div[@class=&quot;quill&quot;]/div[@class=&quot;ql-container ql-snow&quot;]/div[@class=&quot;ql-editor ql-blank&quot;]</value>
      <webElementGuid>37fabfff-8786-47e4-a9d1-eca18d21362c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[3]/div/div/div/div[2]/div/div/div[3]/div/div/div/div[2]/div</value>
      <webElementGuid>549fad89-e1f9-4a61-8e93-439086a57def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Address *'])[1]/following::div[5]</value>
      <webElementGuid>6979e6cc-0090-4ea3-b345-d2ae50419f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose customer group'])[1]/following::div[10]</value>
      <webElementGuid>35fb5e73-c4a5-48ae-af6a-c7b7242813cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Email'])[1]/preceding::div[4]</value>
      <webElementGuid>809adf9d-94ff-4bfa-bf46-4e533a01dc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Telp'])[1]/preceding::div[8]</value>
      <webElementGuid>68ef1d57-1a24-4743-bc73-a4fc7fd298ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div/div/div[2]/div</value>
      <webElementGuid>25fd8b9c-6fc9-4146-80f4-5fdc3e46e1e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
