<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_processing_shipment</name>
   <tag></tag>
   <elementGuidId>8e577109-ded4-4023-978f-1484965f6a0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div[1]/div[1]/div/div/div/div[1]/div[2]/ul/li[7]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56821bd1-5ea6-47ba-9e3b-8a4d4a7de738</webElementGuid>
   </webElementProperties>
</WebElementEntity>
