<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_archive_cancelled</name>
   <tag></tag>
   <elementGuidId>d34015b0-2875-4e82-a991-e36c7ebfb3a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'nav-sub-link w-100 bg-transparent border-0 ' and (text() = 'Cancelled' or . = 'Cancelled')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc41ac9e-c850-4482-9a40-44290110fd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-sub-link w-100 bg-transparent border-0 </value>
      <webElementGuid>9e768484-8e16-4898-b705-759e17bcc690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancelled</value>
      <webElementGuid>5dc69deb-cc09-46c8-916b-d69de2ff69a1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
