<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_new_shipment</name>
   <tag></tag>
   <elementGuidId>e5467908-da7f-4431-b5a3-5c12a86d9521</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '/origin/shippinginstruction/form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e535a3b-a9ea-4d7e-9e3f-f24f52f03f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>/origin/shippinginstruction/form</value>
      <webElementGuid>77ef45fc-6e38-4e81-8d98-8c463afe82d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Shipment</value>
      <webElementGuid>f3f5ebb6-90ed-497c-a10f-bb6b791725da</webElementGuid>
   </webElementProperties>
</WebElementEntity>
