<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_sea_freight</name>
   <tag></tag>
   <elementGuidId>3c3bd752-ed70-464a-b6c2-2d4554873fa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/origin/loadingreport/' and (text() = 'Sea Freight' or . = 'Sea Freight')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>439528f4-143d-46e7-8189-4810e3d56c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/origin/loadingreport/</value>
      <webElementGuid>cd8178a3-1f6b-4f47-a353-5c86ddceeade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sea Freight</value>
      <webElementGuid>93efbb6e-07c8-4022-bf52-8043834affa4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
