<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Customer</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c5b60f7e-ea7e-4093-9e73-82df73d740fe</testSuiteGuid>
   <testCaseLink>
      <guid>2c9cb8ca-c6ca-49a8-b434-72a4dd259c36</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/general/TC_Open_Browser</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>023ea33d-6ff6-49be-8418-c6a323a3f347</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/general/TC_Open_Url</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea4f5c1d-7c79-4e3d-94d9-94887f415547</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11ee4e77-54af-46fa-bb22-027730422d6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login/TC_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7f02aabb-629d-4054-94fd-ef0493e366f4</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/login/TD_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7f02aabb-629d-4054-94fd-ef0493e366f4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>EMAIL</value>
         <variableId>4e97d4b0-54b5-4eb6-b31a-29c1696b76cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7f02aabb-629d-4054-94fd-ef0493e366f4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PASSWORD</value>
         <variableId>8ab98a93-e489-462c-bbb7-a7b50ea30545</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>412b61e9-f5d2-4ed5-9310-51e684bcc629</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/customer/TC_Form_Add_Customer</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4060335-7c6c-448d-a6f4-7b19cbf3bc6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc262551-fe80-419b-8d0b-84714a14842e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28009068-f966-4d26-aa41-c6875d10bf84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a77b62da-0e5d-4442-897d-ed9a12bbf621</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46b90e21-047c-4f13-aca5-47fea00c61a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>21898f7d-650f-4dab-8ca6-12121a4d357b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/customer/TC_Submit_Fill_Mandatory</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d0da443-294c-4fe0-ae57-9ec562550357</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
