<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Origin_Dashboard</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2979afb3-bfa7-44ab-8a40-e9e2860f3c15</testSuiteGuid>
   <testCaseLink>
      <guid>bae5993e-dc42-4908-a2ec-69c9d11d71e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/general/TC_Open_Browser</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5b17e8bb-7ed3-4a7d-ac19-1b81885b2d52</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/general/TC_Open_Url</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea4f5c1d-7c79-4e3d-94d9-94887f415547</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f7df127-2c9f-4ca7-8282-0c9867895303</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login/TC_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>255ff2dd-387a-446e-87bb-f709d92293d5</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/login/TD_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>255ff2dd-387a-446e-87bb-f709d92293d5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>EMAIL</value>
         <variableId>4e97d4b0-54b5-4eb6-b31a-29c1696b76cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>255ff2dd-387a-446e-87bb-f709d92293d5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PASSWORD</value>
         <variableId>8ab98a93-e489-462c-bbb7-a7b50ea30545</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8ed53d1-f08e-427e-aac9-a89514a6b39a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/dashboard/TC_Origin_Dashboard</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
